alias comedit='cd;nano ~/Github/dotfiles_rpi/.pi_bash.sh' #Edits THIS file
alias custedit='cd;nano ~/Github/dotfiles_rpi/.commands' #Edits txt file
alias custom='cd;figlet Custom | lolcat;cat ~/Github/dotfiles_rpi/.commands | lolcat'
alias temp='vcgencmd measure_temp | lolcat'
alias speed='vcgencmd measure_clock arm | lolcat'
alias info='vcgencmd measure_clock arm | lolcat; vcgencmd measure_temp | lolcat'
alias deluge='deluged;deluge-console;'
alias server='cd;cd Server'
alias shutdown='sudo shutdown now'
