alias comedit='cd;nano ~/.pi_bash.sh' #Edits THIS file
alias custedit='cd;nano ~/.custom' #Edits txt file
alias custom='cd;figlet Custom | lolcat;cat ~/.custom | lolcat'
alias temp='vcgencmd measure_temp | lolcat'
alias speed='vcgencmd measure_clock arm | lolcat'
alias info='vcgencmd measure_clock arm | lolcat; vcgencmd measure_temp | lolcat'
alias deluge='deluged;deluge-console;'
alias server='cd;cd Server'
alias now='timedatectl'
